# Generated by Django 3.0.1 on 2019-12-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='owner',
        ),
    ]
