# Generated by Django 3.0.1 on 2020-01-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_receipt_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='enter_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='exit_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
